### ISSUE TITLE
Regexes that match the empty string send ack into an infinite loop

### ISSUE THREAD

**Issue by epa** [beyondgrep/ack2#542] opened 2015-03-25 14:33 UTC
You can grind ack to a halt with

% ack '.*'

Although `.*` is not slow for the regexp engine to match, it slows down ack a lot.  Is there something ack could do more intelligently?

**Comment by petdance** [comment] 2015-03-25 14:38
Why would you want to ack for `.*` in the first place?

**Comment by epa** [comment] 2015-03-25 14:44
Obviously you wouldn't, but it is the simplest example that illustrates the slowdown.  I stumbled across this when I had intended to find `[.][*]` but accidentally typed `[.]*`.  I imagine that fixing the slowdown for `.*` would also have a beneficial effect for other regexps that are not quite as pathological, but nonetheless slow.  But if that's not likely to be the case, feel free to disregard the issue.

**Comment by petdance** [comment] 2015-03-25 14:51
I'd like to find a realistic example that is worth pursuing.  I don't know why it locks up on `.*` but it's hard for me to get interested in it in the face of other, real bugs that are out there.

Still, let's leave this open.

**Comment by hoelzro** [comment] 2015-03-25 15:15
Did a bit of digging; it's not just slow; it ends up in an infinite loop that consumes all memory in sight.  The problem is in `print_line_with_options`; the coloration logic increases the length of the string, causing the pattern to match something new all the time.

**Comment by epa** [comment] 2015-03-25 15:17
Ouch, colorizing the string changes what the regexp matches?  Maybe there is a test case for that bug all by itself without using `.*`.

**Comment by hoelzro** [comment] 2015-03-25 15:19
@epa I think `.*` is special, because it matches both the entire line, but also the empty string.

**Comment by petdance** [comment] 2015-03-25 15:57
And it's not just `.*`, but stuff like `b*` which I could easily see people doing by mistake.

**Comment by epa** [comment] 2015-03-25 16:03
Maybe the first thing ack should do is test the given regexp against the empty string, and if it matches die with an error?  That doesn't rule out fixing the underlying code in `print_line_with_options` of course.  But surely nobody deliberately searches for the empty string.

**Comment by petdance** [comment] 2015-03-25 16:06
That seems like a good check.  If it matches the empty string, then the user has entered something incorrectly.  But what would we describe to the user in the error message?

Imagine the user is looking for something like "a*b*c*", for whatever they think that that will do.  How do we describe the problem?

**Comment by epa** [comment] 2015-03-25 16:13
````The regular expression X matches the empty string, so it cannot be used to search for text.````

There's probably no message you can write which will explain the problem clearly to someone who doesn't understand regular expressions.

**Comment by pdl** [comment] 2015-03-25 21:22
"Maybe the first thing ack should do is test the given regexp against the empty string"

This will fail for `(?<=.).*` and probably some genuinely realistic cases including zero-width assertions.

Perhaps a better solution would be to determine whether `$&` is zero-length (by looking at the start and end position matched via the other punctuation variables to avoid the penalty of  `$&`) - if it is of zero length then do not colourise.

**Comment by hoelzro** [comment] 2015-03-25 21:28
@pdl That would be my chosen approach, and a quick test I tried got it out of the highlighting loop.  There was another one it was stuck in though; I'm going to investigate further when I have some more time.

**Comment by petdance** [comment] 2015-03-25 21:28
Agreed that checking for `$&` being zero-length is probably a win.

I'd like to see some genuinely realistic cases with zero-width assertions before we say that "We shouldn't forbid them because they might get used."

**Comment by epa** [comment] 2015-03-25 21:43
@pdl are you saying there are regexps which do match the empty string but are nonetheless useful to search with?

**Comment by hoelzro** [comment] 2015-03-26 01:15
Ok, the bug is fixed as of 80402b4.

**Comment by petdance** [comment] 2015-03-26 03:06
Thanks for fixing this, @hoelzro.  Can you please put a comment on the check that explains why it's there?

**Comment by hoelzro** [comment] 2015-03-26 03:33
@petdance Done!

**Comment by hoelzro** [comment] 2015-04-05 06:25
Can we close this?

**Comment by Gunni** [comment] 2015-07-16 15:48
Not tested with the latest commit but for me this happened with

    ack ''

**Comment by pplu** [comment] 2016-01-28 22:37
I've found the same thing with `ack $ file`. It would look like the same bug, but I just wanted to advise you guys of more ways to trigger the bug

**Closed** 2019-09-28 16:07 UTC
Labels: PRIORITY 1, ack3, bug, highlighting
